/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package casino;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import casino.blackjack.BlackJack;
import casino.poker.Poker;
import casino.shared.BettingSystem;

class AppTest {
    @Test void testRunCasinoCaseSensitive() {
        
    }

    // @Test void pokerHandIsFlush() {
    //     PokerHand classUnderTest = new PokerHand();
    //     assertNotNull(classUnderTest.isFlush(), "should be a flush");
    // }

}
